### ISSUE TITLE
Too ugly,  4A watermelon

### ISSUE THREAD

**Issue by shenlebantongying** [pymongo/leetcode-rust#1]
https://github.com/pymongo/leetcode-rust/blob/20d0a847ce786fff352095715d9aa9d3f068c222/src/easy/codeforces_easy.rs#L55-L60
can simply done by 
```rust
// optimal, in-place trim 
read_buffer.truncate(read_buffer.trim_end().len());

// less optimal, extra allocation
read_buffer= read_buffer.trim().parse().unwrap();
```
Example submissions:
https://codeforces.com/contest/4/submission/118260875
https://codeforces.com/contest/4/submission/118261880

**Comment by pymongo** [comment]
Thanks for your suggestion, I refactor to this:

https://github.com/pymongo/leetcode-rust/blob/f2f36c2736b610731271df74b5315eca252104a4/src/easy/codeforces_easy.rs#L51-L53
